name: "mozart_etl"
version: "1.0.0"
config-version: 2

profile: "mozart_etl"
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +tags: ["model"]
  +meta:
    dagster:
      owners: ["team:data"]

  mozart_etl:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table

vars:
  min_date: "2000-01-01"
  max_date: "9999-12-31"
  tenants: ["project_01", "project_02"]
