---
mozart_etl:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: trino
      method: none
      host: "{{ env_var('TRINO_HOST', '192.168.1.250') }}"
      port: "{{ env_var('TRINO_PORT', '18080') | int }}"
      user: "{{ env_var('TRINO_USER', 'admin') }}"
      http_scheme: "{{ env_var('TRINO_HTTP_SCHEME', 'http') }}"
      database: "{{ env_var('TRINO_CATALOG', 'iceberg') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dev') }}"
      threads: 4

    prod:
      type: trino
      method: ldap
      host: "{{ env_var('TRINO_HOST', '192.168.1.250') }}"
      port: "{{ env_var('TRINO_PORT', '18080') | int }}"
      user: "{{ env_var('TRINO_USER', 'admin') }}"
      password: "{{ env_var('TRINO_PASSWORD', '') }}"
      http_scheme: "{{ env_var('TRINO_HTTP_SCHEME', 'http') }}"
      database: "{{ env_var('TRINO_CATALOG', 'iceberg') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      threads: 8
