---
mozart_etl:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: trino
      method: none
      host: "{{ env_var('TRINO_HOST', 'localhost') }}"
      port: 8080
      user: trino
      database: iceberg
      schema: "{{ env_var('DBT_SCHEMA', 'dev') }}"
      threads: 4

    prod:
      type: trino
      method: ldap
      host: "{{ env_var('TRINO_HOST', 'localhost') }}"
      port: 8080
      user: "{{ env_var('TRINO_USER', 'trino') }}"
      password: "{{ env_var('TRINO_PASSWORD', '') }}"
      database: iceberg
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      threads: 8
