version: 2

sources:
  - name: project_01
    description: "Iceberg tables for project_01 tenant"
    database: iceberg
    schema: project_01
    tables:
      - name: cfg_item_master
        description: "Item master configuration for project_01"
        meta:
          dagster:
            asset_key: ["project_01", "transform", "cfg_item_master"]

  - name: project_02
    description: "Iceberg tables for project_02 tenant"
    database: iceberg
    schema: project_02
    tables:
      - name: cfg_item_master
        description: "Item master configuration for project_02"
        meta:
          dagster:
            asset_key: ["project_02", "transform", "cfg_item_master"]
