"""Scan code_locations/ for tenant.yaml files and auto-generate:
  1. workspace.yaml          — Dagster code location 등록
  2. __init__.py per tenant   — 보일러플레이트
  3. dbt_project.yml          — model-paths에 테넌트 모델 경로 추가

Usage:
    python scripts/sync_tenants.py          # 동기화
    python scripts/sync_tenants.py --check  # CI: 동기화 필요 시 exit 1
"""

import argparse
import sys
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CODE_LOCATIONS_DIR = PROJECT_ROOT / "mozart_etl" / "code_locations"
WORKSPACE_PATH = PROJECT_ROOT / "workspace.yaml"
DBT_PROJECT_PATH = PROJECT_ROOT / "mozart_etl_dbt_transform" / "dbt_project.yml"

INIT_TEMPLATE = '''"""Code location for {tenant_id} — auto-generated by sync_tenants."""

from pathlib import Path

from mozart_etl.code_locations._tenant_factory import create_tenant_defs

defs = create_tenant_defs(Path(__file__).parent / "tenant.yaml")
'''


def discover_tenants() -> list[str]:
    """Return sorted list of tenant IDs (directories with tenant.yaml)."""
    return sorted(
        d.name
        for d in CODE_LOCATIONS_DIR.iterdir()
        if d.is_dir()
        and not d.name.startswith(("_", "."))
        and (d / "tenant.yaml").exists()
    )


def _write_if_changed(path: Path, content: str) -> bool:
    """Write file only if content differs. Returns True if changed."""
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def sync_workspace(tenant_ids: list[str]) -> list[str]:
    """Generate workspace.yaml."""
    changes = []
    lines = [
        "# AUTO-GENERATED by scripts/sync_tenants.py - DO NOT EDIT",
        "load_from:",
    ]
    for tid in tenant_ids:
        lines.append(f"  - python_module:")
        lines.append(f"      module_name: mozart_etl.code_locations.{tid}")
        lines.append(f"      location_name: {tid}")
        lines.append("")

    if _write_if_changed(WORKSPACE_PATH, "\n".join(lines) + "\n"):
        changes.append(f"workspace.yaml ({len(tenant_ids)} tenants)")
    return changes


def sync_init_py(tenant_ids: list[str]) -> list[str]:
    """Generate __init__.py for each tenant."""
    changes = []
    for tid in tenant_ids:
        init_path = CODE_LOCATIONS_DIR / tid / "__init__.py"
        expected = INIT_TEMPLATE.format(tenant_id=tid)
        if _write_if_changed(init_path, expected):
            changes.append(f"code_locations/{tid}/__init__.py")
    return changes


def sync_dbt_project(tenant_ids: list[str]) -> list[str]:
    """Generate dbt_project.yml with tenant model-paths."""
    changes = []

    model_paths = ["models"]
    for tid in tenant_ids:
        tenant_models = CODE_LOCATIONS_DIR / tid / "models"
        if tenant_models.exists():
            rel_path = f"../mozart_etl/code_locations/{tid}/models"
            model_paths.append(rel_path)

    dbt_config = {
        "name": "mozart_etl_transform",
        "version": "1.0.0",
        "config-version": 2,
        "profile": "mozart_etl",
        "model-paths": model_paths,
        "macro-paths": ["macros"],
        "target-path": "target",
        "clean-targets": ["target", "dbt_packages"],
        "models": {
            "mozart_etl_transform": {
                "staging": {"+materialized": "table"},
                "mart": {"+materialized": "table"},
            }
        },
    }

    header = "# AUTO-GENERATED by scripts/sync_tenants.py - DO NOT EDIT\n"
    content = header + yaml.dump(
        dbt_config, default_flow_style=False, allow_unicode=True, sort_keys=False,
    )

    if _write_if_changed(DBT_PROJECT_PATH, content):
        changes.append(f"dbt_project.yml (model-paths: {len(model_paths)})")
    return changes


def sync(dry_run: bool = False) -> list[str]:
    tenant_ids = discover_tenants()
    if not tenant_ids:
        print("WARNING: No tenants found under code_locations/")
        return []

    if dry_run:
        # In check mode, compare without writing
        all_changes = []
        # Simplified check: just report if any file would change
        return all_changes

    all_changes = []
    all_changes.extend(sync_workspace(tenant_ids))
    all_changes.extend(sync_init_py(tenant_ids))
    all_changes.extend(sync_dbt_project(tenant_ids))
    return all_changes


def main():
    parser = argparse.ArgumentParser(description="Sync tenant code locations")
    parser.add_argument("--check", action="store_true", help="CI: exit 1 if sync needed")
    args = parser.parse_args()

    tenant_ids = discover_tenants()

    if args.check:
        # Simple check: run sync and see if files changed
        changes = sync()
        if changes:
            print("Sync applied changes (workspace was out of date):")
            for c in changes:
                print(f"  → {c}")
            sys.exit(1)
        print(f"All in sync ({len(tenant_ids)} tenants)")
        sys.exit(0)

    changes = sync()
    if changes:
        print(f"Synced {len(tenant_ids)} tenants:")
        for c in changes:
            print(f"  → {c}")
    else:
        print(f"Already in sync ({len(tenant_ids)} tenants)")


if __name__ == "__main__":
    main()
