# MODIFIED: Using models directory instead of relative paths
name: mozart_etl_transform
version: 1.0.0
config-version: 2
profile: mozart_etl
model-paths:
- models
macro-paths:
- macros
target-path: target
clean-targets:
- target
- dbt_packages
models:
  mozart_etl_transform:
    project_01:
      staging:
        +materialized: table
      mart:
        +materialized: table
    project_02:
      staging:
        +materialized: table
      mart:
        +materialized: table
