version: 2

models:
  - name: mart_cfg_item_master_all
    description: "Consolidated cfg_item_master across all tenants"
    columns:
      - name: tenant_id
        description: "Tenant identifier (project_01, project_02, etc.)"
        tests:
          - not_null
      - name: item_id
        description: "Item identifier"
        tests:
          - not_null
